trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Print Hello
  jobs:
  - job: Build
    displayName: Print Hello
    pool:
      name: Default   # <-- self-hosted agent pool
    steps:
    - script: echo "hello"
      displayName: Say Hello
