name: CI/CD for LibreChat

on:
  push:
    branches:
      - main     # Run pipeline when you push to main branch

jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Step 1: Checkout your code
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Step 2: Log in to Docker Hub
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     # Step 3: Build and push Docker image
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         no-cache: true
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/jeel:latest
  #           ${{ secrets.DOCKERHUB_USERNAME }}/jeel:${{ github.sha }}

  deploy-cloudrun:
    #needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      # This step should now work, provided the GCP_SA_KEY secret is properly set.
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }} # This secret MUST be set in GitHub
    
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
    
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE }} \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/jeel:latest \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
